AdminURL: https://testadmin.xiaopay.net
XiaopayURL: https://test.xiaopay.net
log:
    file_name: API_test.log
    backup: 10
    console_level: WARNING
    file_level: INFO
    pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'